%  read data... 
% this function is reading excel data. 
% Data must have a specific format: there should be three columns, the
% first column contains the maneuver IDs, the second column contains the
% time stamps generated by the TrafficTurk application and the third column
% has the correct phases. The correct phases are manually determined to
% check the inference results of the algorithm. 

%input: the string: name of the data file. 
% output: matlab .mat file. 

function data = readExcelData(fileName)
    
    temp_data = xlsread(fileName);
    
    if size(temp_data)<2
            error('data set should have both maneuver ID and time stamps')
    elseif size(temp_data)<3
            warning('There are probably no real phases in the data set, consider adding it to the data set')
            data=temp_data;
    else
            data=temp_data;

    end
    
end